import { Theme } from "./theme.slint";
import { CollectionSection } from "./components/collections.slint";
import { RequestsSection } from "./components/requests.slint";
import { HeadersSection } from "./components/headers.slint";
import { IconsPopup } from "./components/icons_popup.slint";
import { CollectionsDropDown } from "./components/collection_dropdown.slint";
import { RequestsDropDown } from "./components/request_dropdown.slint";
import { FooterSection } from "./components/footer.slint";


export component MainPage inherits Rectangle {
    in-out property <float> handle_position: 0.15;
    in-out property <float> new_pos;

    handle := Rectangle {
        x: root.handle_position * parent.width;
        width: 5px;
        height: parent.height;
        border-color: Theme.app_background_color;
    }

    touch := TouchArea {
        x: handle.x - self.width / 2;
        width: 10px;
        height: parent.height;
        mouse-cursor: col-resize;

        moved => {
            if (self.pressed) {
                new_pos = (self.mouse-x + self.x) / parent.width;
                if (new_pos >= 0.04 && new_pos <= 0.96) {
                    handle_position = new_pos;
                }
            }
        }
    }


    left := CollectionSection {
        z: 1;
        x: parent.x;
        width: handle.x - handle.width / 2;
    }

    right := VerticalLayout {
        z: 2;
        width: (1 - root.handle_position) * parent.width;
        x: left.width + handle.width / 2;

        HeadersSection {}
        RequestsSection {
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }
        FooterSection {}
    }

    IconsPopup {z: 5;}
    CollectionsDropDown {}
    RequestsDropDown {}
}