name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt install libgtk-4-dev build-essential -y
        sudo apt install libadwaita-1-dev -y
    
    - name: Build
      run: |
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
